language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: pSotsa02I2ZtZ0U6elCHEus1JlFyD2PZVHlD610ZbYg2c4lXCg1drYVetvOPQ+lcdVdDP/3kkjDJEjGn0QXYaSZjU+ewb4WKYkr4oN0gmNbYZAvUwBwpFK9ruyfswKP0uEcaoDCT9TwHoaCTweM5UF6YyhCaD8KeNdidYvvy0T2OCIf36i3bWKUN5nxdOshCo/vKH6Iem5Nc9DmlqbBn9XTcwC7VwqV38SJvVvlvdaEh4SF4C7PKHQh4v2vTx/PLdt2efGbEhYYlrbXldZXqVwUz/tgG2KFseOpcHQcXtuc4APxTQ4R2WGqRu2flH5NGBPSsC/SINQSnfYwwtl5Z0/4GERgNq6ic+THokO2ixZS30fJbJqyjUy+8fq/Td1PrZ3lXrxPXC51AQKwMa7EROXb60BoWIgJKyLODDOkIOWOoFpK5Qo1CZFLb9b/plLJTwXiiArJbtyx9MzKrciE4HGtRjbUL6EdbTbponJmfQ9QJL5vysIfxR87d1xGbOd8QwUTdlmgM1JswzQMj8MgvQUZoqQVFRk6VedZg4KoGZ4wvMvUNvbAV/gwJ8ifzSijploLTsdJzxIlE7nK85loy/8+vLU02h27bCe2+U23E19lI7k4xlajd+DK0JRbHSX1UBg+NZLMJUCZeQa6b9Zq8F6xWJf3CGFhMPoeIjs/NMCw=
  app: still-scrubland-12044
  on:
    repo: iastanley/node-shopping-list-integration-tests
